FROM arm32v6/python:3.7-alpine
MAINTAINER Eduard Asriyan <ed-asriyan@protonmail.com>

WORKDIR /application

RUN apk add gcc musl-dev postgresql-dev --no-cache

ADD requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# for testing
ADD scripts/db_fill_random.py db_fill_random.py

ADD server ./server
ADD config/__init__.py ./config/__init__.py
ADD config/config.hjson ./config/config.hjson
ADD start.py .

CMD python3 ./start.py
