version: '3'

services:
    database:
        build:
            context: https://github.com/M4MController/cloud-web.git
            dockerfile: Dockerfile-db
        environment:
            POSTGRES_USER: "m4m"
            POSTGRES_PASSWORD: "12345"
            POSTGRES_DB: "m4m"
        restart: always
        ports:
            - 5432:5432
    backend:
        build:
            context: https://github.com/M4MController/cloud-web.git#develop
            dockerfile: Dockerfile
        ports:
            - 5000:5000
        depends_on:
            - database
        restart: always
